version: "3"

services:
  payment-db:
    image: bitnami/postgresql
    volumes:
      - payment-db-volume:/bitnami/postgresql
    ports:
      - 5005:5432
    environment:
      - POSTGRESQL_USERNAME=payment-db-read-write
      - POSTGRESQL_PASSWORD=4b0c9f4a-9c1e-4f52-9a2c-2b3a1f5e9d67
      - POSTGRESQL_DATABASE=payment-db

volumes:
  payment-db-volume:
